### ISSUE TITLE
More "plan" errors

### ISSUE THREAD

**Issue by kentfredric** [ehuelsmann/perl-Test-Dependencies#5]
Ugh.

```
_harness(0, 'blib/lib', 'blib/arch')" t/*.t
t/00-load-basic.t ............ 1/? The plan was already output at /usr/lib64/perl5/5.24.0/Test/Builder.pm line 2510.
t/00-load-basic.t ............ All 3 subtests passed 
```

Transposing these `use_ok` lines with `require_ok` lines seems to be sufficient, that way it doesn't try to call `->import` ( which in turn calls `plan` ).

Because this:

``` perl
use Test::More 0.98; 
use lib q[lib]; 
use_ok(q[Test::Dependencies]);
done_testing;  # <-- calls plan .... 
```

This might be a bug in Test::More though and I'll be following that up there. But you can still avoid this problem entirely with `require_` instead of `use_`

**Comment by kentfredric** [comment]
Ok, its not a bug in the "Latest" Test::Simple, that's  fixed. Just a bug on 1.1.14 ( the version that ships with 5.24 )

**Comment by ehuelsmann** [comment]
@kentfredric I'm wondering though, shouldn't `dependencies_ok()` be calling `plan` (with the option to suppress) instead of `->import()`?

**Comment by ehuelsmann** [comment]
or yet even better, shouldn't we just demand from the end-user to call `done_testing;` manually when, well, done testing?

**Comment by kentfredric** [comment]
I'm kinda averse to anything calling plan controls, because it does this sort of thing.

Though I can certainly agree that "avoid it in import" is a better standard than what we have.

I don't know enough here unfortunately, and its a better question for irc.perl.org#perl-qa

**Comment by ehuelsmann** [comment]
Fair enough. I'll head there and see what they have to add to our situation.
